USE [master]
GO

/****** Object:  Database [Parqueadero]    Script Date: 12/12/2022 11:44:55 a. m. ******/
CREATE DATABASE [Parqueadero]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Parqueadero', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Parqueadero.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Parqueadero_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Parqueadero_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Parqueadero].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Parqueadero] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Parqueadero] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Parqueadero] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Parqueadero] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Parqueadero] SET ARITHABORT OFF 
GO

ALTER DATABASE [Parqueadero] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Parqueadero] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Parqueadero] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Parqueadero] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Parqueadero] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Parqueadero] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Parqueadero] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Parqueadero] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Parqueadero] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Parqueadero] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Parqueadero] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Parqueadero] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Parqueadero] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Parqueadero] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Parqueadero] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Parqueadero] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Parqueadero] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Parqueadero] SET RECOVERY FULL 
GO

ALTER DATABASE [Parqueadero] SET  MULTI_USER 
GO

ALTER DATABASE [Parqueadero] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Parqueadero] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Parqueadero] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Parqueadero] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Parqueadero] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Parqueadero] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Parqueadero] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Parqueadero] SET  READ_WRITE 
GO


